"""
Pre-processing module for document normalization
Handles noise removal, date unification, OCR corrections
"""

import re
from typing import Optional
import cv2
import numpy as np
from PIL import Image


class DocumentPreprocessor:
    """Normalizes and cleans extracted text"""
    
    def __init__(self):
        self.date_patterns = [
            r'\d{1,2}[/-]\d{1,2}[/-]\d{2,4}',
            r'\d{4}[/-]\d{1,2}[/-]\d{1,2}',
            r'\d{1,2}\s+\w+\s+\d{4}',
        ]
    
    def normalize_text(self, text: str) -> str:
        """
        Clean and normalize extracted text SERIOUSLY
        
        Args:
            text: Raw extracted text
            
        Returns:
            Normalized text
        """
        if not text:
            return ""
        
        # Step 1: Remove watermarks and scanner artifacts
        text = re.sub(r'Scanned with CamScanner', '', text, flags=re.IGNORECASE)
        text = re.sub(r'Scanned by.*?Scanner', '', text, flags=re.IGNORECASE)
        text = re.sub(r'Generated by.*?PDF', '', text, flags=re.IGNORECASE)
        
        # Step 2: Fix common OCR errors
        ocr_corrections = {
            'INDIRIOZO': 'INDIRIZZO',
            'INDIRIZZO': 'INDIRIZZO',  # Keep correct
            'COGNOME': 'COGNOME',
            'NOME': 'NOME',
            'CODICE FISCALE': 'CODICE FISCALE',
            'CODICE FISCALE': 'CODICE FISCALE',  # Keep correct
        }
        for wrong, correct in ocr_corrections.items():
            text = text.replace(wrong, correct)
        
        # Step 3: Normalize whitespace (but preserve line structure for MRZ)
        text = re.sub(r'[ \t]+', ' ', text)  # Multiple spaces/tabs to single space
        text = re.sub(r'\n{3,}', '\n\n', text)  # Multiple newlines to double
        
        # Step 4: Clean up MRZ artifacts (but keep MRZ lines intact)
        # We'll extract MRZ separately, but clean obvious OCR errors in MRZ format
        lines = text.split('\n')
        cleaned_lines = []
        for line in lines:
            # If line looks like MRZ (lots of < and alphanumeric), keep it but clean
            if re.search(r'[A-Z0-9<]{20,}', line):
                # MRZ line - minimal cleaning
                cleaned_lines.append(line)
            else:
                # Regular text - more aggressive cleaning
                line = line.strip()
                if line:
                    cleaned_lines.append(line)
        
        text = '\n'.join(cleaned_lines)
        
        # Step 5: Remove excessive special characters (but keep MRZ)
        # Don't remove < from MRZ lines
        
        # Step 6: Normalize case (but preserve MRZ which is uppercase)
        # We'll handle case normalization per-field during extraction
        
        # Step 7: Final trim
        text = text.strip()
        
        return text
    
    def normalize_dates(self, text: str) -> str:
        """
        Unify date formats in text
        
        Args:
            text: Text containing dates
            
        Returns:
            Text with normalized dates
        """
        # This is a placeholder - in production you'd convert to ISO format
        # For now, we just ensure consistency
        return text
    
    def preprocess_image(self, image_path: str) -> Optional[np.ndarray]:
        """
        Preprocess image for better OCR results
        
        Args:
            image_path: Path to image file
            
        Returns:
            Preprocessed image array
        """
        try:
            img = cv2.imread(image_path)
            if img is None:
                return None
            
            # Convert to grayscale
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            
            # Denoise
            denoised = cv2.fastNlMeansDenoising(gray, None, 10, 7, 21)
            
            # Threshold
            _, thresh = cv2.threshold(denoised, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
            
            return thresh
        except Exception as e:
            print(f"Error preprocessing image: {e}")
            return None
    
    def preprocess_image_from_array(self, img_array: np.ndarray) -> Optional[np.ndarray]:
        """
        Preprocess image array for better OCR results
        
        Args:
            img_array: Image as numpy array
            
        Returns:
            Preprocessed image array
        """
        try:
            # Denoise
            denoised = cv2.fastNlMeansDenoising(img_array, None, 10, 7, 21)
            
            # Threshold
            _, thresh = cv2.threshold(denoised, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
            
            return thresh
        except Exception as e:
            print(f"Error preprocessing image array: {e}")
            return None
    
    def process(self, text: str) -> str:
        """
        Full preprocessing pipeline
        
        Args:
            text: Raw text
            
        Returns:
            Processed text
        """
        text = self.normalize_text(text)
        text = self.normalize_dates(text)
        return text
